export * from './AuthPage'
export * from './ClothesPage'
export * from './HomePage'
export * from './RegistrationPage'
export * from './ShoesPage'
export * from './SignUpConfirmPage'
export * from './NewPasswordPage'
export * from './SendRecoveryMailPage'
